/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemoteRouteImport } from './routes/remote'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObstaclesRouteImport } from './routes/obstacles'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as IndexRouteImport } from './routes/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObstaclesRoute = ObstaclesRouteImport.update({
  id: '/obstacles',
  path: '/obstacles',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/debug': typeof DebugRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/navigation': typeof NavigationRoute
  '/obstacles': typeof ObstaclesRoute
  '/onboarding': typeof OnboardingRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/tracking': typeof TrackingRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/debug': typeof DebugRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/navigation': typeof NavigationRoute
  '/obstacles': typeof ObstaclesRoute
  '/onboarding': typeof OnboardingRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/tracking': typeof TrackingRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/debug': typeof DebugRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/navigation': typeof NavigationRoute
  '/obstacles': typeof ObstaclesRoute
  '/onboarding': typeof OnboardingRoute
  '/remote': typeof RemoteRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/tracking': typeof TrackingRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companion'
    | '/debug'
    | '/health'
    | '/home'
    | '/login'
    | '/navigation'
    | '/obstacles'
    | '/onboarding'
    | '/remote'
    | '/settings'
    | '/sos'
    | '/tracking'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companion'
    | '/debug'
    | '/health'
    | '/home'
    | '/login'
    | '/navigation'
    | '/obstacles'
    | '/onboarding'
    | '/remote'
    | '/settings'
    | '/sos'
    | '/tracking'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/companion'
    | '/debug'
    | '/health'
    | '/home'
    | '/login'
    | '/navigation'
    | '/obstacles'
    | '/onboarding'
    | '/remote'
    | '/settings'
    | '/sos'
    | '/tracking'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanionRoute: typeof CompanionRoute
  DebugRoute: typeof DebugRoute
  HealthRoute: typeof HealthRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NavigationRoute: typeof NavigationRoute
  ObstaclesRoute: typeof ObstaclesRoute
  OnboardingRoute: typeof OnboardingRoute
  RemoteRoute: typeof RemoteRoute
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
  TrackingRoute: typeof TrackingRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote': {
      id: '/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obstacles': {
      id: '/obstacles'
      path: '/obstacles'
      fullPath: '/obstacles'
      preLoaderRoute: typeof ObstaclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanionRoute: CompanionRoute,
  DebugRoute: DebugRoute,
  HealthRoute: HealthRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NavigationRoute: NavigationRoute,
  ObstaclesRoute: ObstaclesRoute,
  OnboardingRoute: OnboardingRoute,
  RemoteRoute: RemoteRoute,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
  TrackingRoute: TrackingRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
